services:
  app:
    build:
      context: .
    environment:
      SERVER_NAME: abomey.local
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mariadb:11.4
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-app}
      MARIADB_USER: ${MARIADB_USER:-app}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-app}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d:ro

volumes:
  database_data:
