services:
  app:
    volumes:
      - .:/app
      - vendor:/app/vendor
      - caddy_data:/data
    ports:
      - "80:80"
      - "443:443"

  database:
    ports:
      - "3306:3306"

volumes:
  vendor:
  caddy_data:
